apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: demo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wordpress.szkolenie-devops.com
spec:
  rules:
  - host: wordpress.szkolenie-devops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
